name: restful_api_user
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_multipart: ^2.0.1
  intl: ^0.20.2
  path: ^1.9.1
  mime: ^2.0.0
  shelf_hotreload: ^1.5.0
  uuid: ^4.5.1
  mysql_utils: ^2.1.5
  mailer: ^6.4.1
  crypto: ^3.0.3
  postgres: ^2.6.1

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
